version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redisinsight:
    image: redis/redisinsight:latest  # Use this for RedisInsight v3
    container_name: redisinsight
    ports:
      - "5540:5540"  # Change this if you need a different port
    depends_on:
      - redis

volumes:
  redis-data:
