version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.0rc0
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - BACKEND_STORE_URI=sqlite:///mlflow.db
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --host 0.0.0.0
