version: '3.1'

services:
  mongo:
    image: mongo:5
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 6003:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
